name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      suite:
        description: 'Select test suite'
        required: true
        default: regression
        type: choice
        options:
        - smoke
        - sanity
        - regression
  
  schedule:
    - cron: '0 9 * * 1'

jobs:
  playwright-tests:
    name: Playwright Tests (${{ matrix.browser }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run Smoke tests on every push and pull request
      - name: Run Smoke Tests
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: npx playwright test --grep "@smoke" --project=${{ matrix.browser }}

        # Run selected suite manually
      - name: Run Selected Suite
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.suite }}" = "smoke" ]; then
            npx playwright test --grep "@smoke" --project=${{ matrix.browser }}
          elif [ "${{ github.event.inputs.suite }}" = "sanity" ]; then
            npx playwright test --grep "@sanity" --project=${{ matrix.browser }}
          else
            npx playwright test --grep "@regression" --project=${{ matrix.browser }}
          fi

      # Run Regression on scheduled execution
      - name: Run Scheduled Regression
        if: github.event_name == 'schedule'
        run: npx playwright test --grep "@regression" --project=${{ matrix.browser }}

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-HTML-Report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30   

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.browser }}
          path: test-results/
          retention-days: 30